### PR TITLE
feat: alert when no backups in 24 hours

### LINKED ISSUE #2: Velero alert on number of completed backups
At the moment we are only checking that the ark pod is running, but not if backups are successful. Might be useful to check that over a period of time the ratio between failed and completed backups does not go over a given threshold.

### PR DESCRIPTION
**Pull request by ralgozino**
Add a custom Prometheus Alert for when there are no successful backups in the last 24 hours.

fixes #2

### CODE REVIEW

**Review by nutellinoit — APPROVED** [review]
LGTM 🎉

**Comment by ralgozino** [comment]
The only downside with the current form of this alert is that it will be triggered when **any** schedule has not run successfully in the last 24 hours. For the schedules included in the modules this is OK, but if somebody adds a new schedule that runs, let's say, once a week, the alert will be triggered with a false positive.

I'm keen to filter the query to only the 2 schedules provided with the module to avoid false positives, but on the other hand the alert could be handy for custom schedules also.

Thoughts @lnovara @nutellinoit ?

**Comment by ralgozino** [comment]
I limited the alert to the schedules provided by the module to not trigger false positives in case there are additional schedules defined that run in periods > 24 hours.

**Review by nutellinoit — APPROVED** [review]
LGTM 🎉

**Review by lnovara — APPROVED** [review]
SBAM :shipit: 

(Sorry for the massively delayed review 😞)

**Pull request merged**
