### PR TITLE
Added gcp-velero module

### PR DESCRIPTION
**Pull request by simonemex**

### CODE REVIEW

**Comment by angelbarrera92** [comment]
Hi, this PR was opened last year. Should we continue with it?

**Comment by lnovara** [comment]
@angelbarrera92 Hi think we should finish the work started in this PR and merge it. Do you agree?

@simonemex can you add the creation of a GCP Service Account to be used by Velero as part of this PR?

Thank you.

**Comment by simonemex** [comment]
Ok I'll do it

**Comment by angelbarrera92** [comment]
Hold on. I am rewriting the entire module ;)

**Comment by angelbarrera92** [comment]
Hi guys. Can you take a look here: https://github.com/sighupio/fury-kubernetes-dr/tree/feature/deprecate-and-update/modules/gcp-velero?

I need your help with the DR module ;)

Thanks!

**Comment by lnovara** [comment]
Superseded by #10, closing.

**Pull request closed without merging**
