### PR TITLE
Fix broken aws-velero Terraform module

### PR DESCRIPTION
**Pull request by lnovara**
Trying to use the `aws-module` currently yields the following error:

```
│ Error: Invalid index
│
│   on ../vendor/modules/dr/aws-velero/output.tf line 18, in locals:
│   18:     aws_access_key_id=${aws_iam_access_key.velero_backup.0.id}
│     ├────────────────
│     │ aws_iam_access_key.velero_backup is empty tuple
│
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│
│   on ../vendor/modules/dr/aws-velero/output.tf line 19, in locals:
│   19:     aws_secret_access_key=${aws_iam_access_key.velero_backup.0.secret}
│     ├────────────────
│     │ aws_iam_access_key.velero_backup is empty tuple
│
│ The given key does not identify an element in this collection value.
```

The aim of this PR is to fix this error and bring a couple of additional improvements, namely:
  - adding back the Kustomize patch for the Deployment resource
  - slightly improving the description of some outputs

### CODE REVIEW

**Review by nutellinoit — CHANGES_REQUESTED** [review]
LGTM,

before merging this PR we need to write the release note for the v1.9.3, update compatibility matrix and change all the reference to the v1.9.2

**Comment by lnovara** [comment]
Done! 🙌

**Review by nutellinoit — APPROVED** [review]
LGTM 🎉

**Comment by nutellinoit** [comment]
Yes, you are right. I will mark the version as "has issues" on the compatibility matrix

**Pull request merged**
