### PR TITLE
added velero-azure Terraform module

### PR DESCRIPTION
**Pull request by lnovara**
The aim of this PR is to create a Terraform module to provision the needed cluod resources for Velero to operate correctly on Azure Cloud.

### CODE REVIEW

**Comment by angelbarrera92** [comment]
This pr was opened last year... Should we continue?

**Comment by angelbarrera92** [comment]
Hold on, i am rewriting the entire module

**Comment by angelbarrera92** [comment]
Hi team!!!
Can you take a look to this module: https://github.com/sighupio/fury-kubernetes-dr/tree/feature/deprecate-and-update/modules/azure-velero

I need your help with azure...

Thanks!

**Comment by lnovara** [comment]
Superseded by #10, closing.

**Pull request closed without merging**
